# Site Info
title: "Jake's Profile"
tagline: "test"
description: "desc"
baseurl: ""
url: https://variu.github.io
logo: ""

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
#paginate:
#paginate_path: ''
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 박종기
  description: Jake Park
  contact:
    # linkedin:  https://www.linkedin.com/in/
    github:    https://github.com/variu
#    facebook:
    # twitter:
    # weibo:
    email:    mailto:variu0120@gmail.com

# Navigation (2nd level links supported)
#nav:
#  Home:
#    - '/blog/'
#  Categories:
#    - '/'

#  About:
#    - '/about/'
#  Search:
#    - '/search/'

# Where are tags and categories displayed
#tag_page: '/'
#category_page: '/'


# Puglins
#mathjax: true # whether support mathjax
#google_analytics_token: '' # leave blank if you don't want google analytics
#disqus_short_name: '' # leave blank if you don't want disqus

